### ISSUE TITLE
[BUG] Missing file information when trying to upload a .msi file

### ISSUE THREAD

**Issue by ivancarlosti** [WeebDev/lolisafe#741]
**Describe the bug**
When I try to upload a .msi file, it returns "Missing file information" alert box

**To Reproduce**
1. Open chibisafe
2. Try to upload file
3. See error

**Expected behavior**
Successful upload

**Screenshots**
![Image](https://github.com/user-attachments/assets/5f16ea08-7532-4516-ab3b-5e1234855549)

**Additional context**
I do not have extension restriction on settings
I store files on AWS S3

Follow my docker-compose deployment:

```
services:
  chibisafe:
    image: chibisafe/chibisafe:latest
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    expose:
      - 8001
    ports:
      - 8001:8001
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 768M

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    volumes:
      - ./database:/app/database:rw
      - ./uploads:/app/uploads:rw
      - ./logs:/app/logs:rw
    expose:
      - 8000
    ports:
      - 8000:8000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 768M
```
